import type { SourceType } from '../types';

export interface SourceDef {
  name: string;
  url: string;
  feed_url: string;
  source_type: SourceType;
  credibility_score: number;
}

export const DEFAULT_SOURCES: SourceDef[] = [
  {
    name: 'Krebs on Security',
    url: 'https://krebsonsecurity.com',
    feed_url: 'https://krebsonsecurity.com/feed/',
    source_type: 'rss',
    credibility_score: 0.95,
  },
  {
    name: 'The Hacker News',
    url: 'https://thehackernews.com',
    feed_url: 'https://feeds.feedburner.com/TheHackersNews',
    source_type: 'rss',
    credibility_score: 0.82,
  },
  {
    name: 'PortSwigger Research',
    url: 'https://portswigger.net/research',
    feed_url: 'https://portswigger.net/research/rss',
    source_type: 'rss',
    credibility_score: 0.93,
  },
  {
    name: 'Google Project Zero',
    url: 'https://googleprojectzero.blogspot.com',
    feed_url: 'https://googleprojectzero.blogspot.com/feeds/posts/default',
    source_type: 'atom',
    credibility_score: 0.97,
  },
  {
    name: 'GitHub Security Lab',
    url: 'https://securitylab.github.com',
    feed_url: 'https://github.blog/tag/security-research/feed/',
    source_type: 'rss',
    credibility_score: 0.92,
  },
  {
    name: 'CISA Advisories',
    url: 'https://www.cisa.gov',
    feed_url: 'https://www.cisa.gov/uscert/ncas/alerts.xml',
    source_type: 'rss',
    credibility_score: 1.0,
  },
  {
    name: 'OWASP Blog',
    url: 'https://owasp.org',
    feed_url: 'https://owasp.org/feed.xml',
    source_type: 'rss',
    credibility_score: 0.97,
  },
  {
    name: 'Snyk Security Blog',
    url: 'https://snyk.io/blog',
    feed_url: 'https://snyk.io/blog/feed/',
    source_type: 'rss',
    credibility_score: 0.85,
  },
  {
    name: 'Auth0 Blog',
    url: 'https://auth0.com/blog',
    feed_url: 'https://auth0.com/blog/rss.xml',
    source_type: 'rss',
    credibility_score: 0.80,
  },
  {
    name: 'Troy Hunt Blog',
    url: 'https://www.troyhunt.com',
    feed_url: 'https://feeds.feedburner.com/TroyHunt',
    source_type: 'rss',
    credibility_score: 0.90,
  },
  {
    name: 'Schneier on Security',
    url: 'https://www.schneier.com',
    feed_url: 'https://www.schneier.com/feed/atom/',
    source_type: 'atom',
    credibility_score: 0.93,
  },
  {
    name: 'Dark Reading',
    url: 'https://www.darkreading.com',
    feed_url: 'https://www.darkreading.com/rss.xml',
    source_type: 'rss',
    credibility_score: 0.78,
  },

  // IAM / OAuth 2.0 / OIDC
  {
    name: 'Okta Security Blog',
    url: 'https://sec.okta.com',
    feed_url: 'https://sec.okta.com/feed',
    source_type: 'rss',
    credibility_score: 0.88,
  },
  {
    name: 'Microsoft Entra Identity Blog',
    url: 'https://techcommunity.microsoft.com/t5/microsoft-entra-blog/bg-p/Identity',
    feed_url: 'https://techcommunity.microsoft.com/t5/microsoft-entra-blog/bg-p/Identity/rss-board-message',
    source_type: 'rss',
    credibility_score: 0.90,
  },
  {
    name: 'Aaron Parecki (OAuth)',
    url: 'https://aaronparecki.com',
    feed_url: 'https://aaronparecki.com/feed.xml',
    source_type: 'atom',
    credibility_score: 0.92,
  },
  {
    name: 'Ping Identity Blog',
    url: 'https://www.pingidentity.com/en/company/blog.html',
    feed_url: 'https://www.pingidentity.com/feed.xml',
    source_type: 'rss',
    credibility_score: 0.83,
  },
  {
    name: 'ForgeRock / Ping Identity Community',
    url: 'https://backstage.forgerock.com/knowledge/blogs',
    feed_url: 'https://community.pingidentity.com/t5/s/global-rss-board-message',
    source_type: 'rss',
    credibility_score: 0.82,
  },
  {
    name: 'Identity Defined Security Alliance',
    url: 'https://www.idsalliance.org/blog',
    feed_url: 'https://www.idsalliance.org/blog/feed/',
    source_type: 'rss',
    credibility_score: 0.85,
  },
  {
    name: 'OpenID Foundation Blog',
    url: 'https://openid.net/blog',
    feed_url: 'https://openid.net/blog/feed/',
    source_type: 'rss',
    credibility_score: 0.93,
  },
  {
    name: 'Duo Security Blog',
    url: 'https://duo.com/blog',
    feed_url: 'https://duo.com/blog/rss',
    source_type: 'rss',
    credibility_score: 0.87,
  },
  {
    name: 'BeyondTrust Blog',
    url: 'https://www.beyondtrust.com/blog',
    feed_url: 'https://www.beyondtrust.com/blog/feed/',
    source_type: 'rss',
    credibility_score: 0.84,
  },
  {
    name: 'CyberArk Blog',
    url: 'https://www.cyberark.com/resources/blog',
    feed_url: 'https://www.cyberark.com/resources/blog/feed/',
    source_type: 'rss',
    credibility_score: 0.85,
  },

  // AI Security & AI Learning
  {
    name: 'Google DeepMind Blog',
    url: 'https://deepmind.google/blog',
    feed_url: 'https://deepmind.google/blog/rss.xml',
    source_type: 'rss',
    credibility_score: 0.95,
  },
  {
    name: 'MIT Technology Review – AI',
    url: 'https://www.technologyreview.com/topic/artificial-intelligence',
    feed_url: 'https://www.technologyreview.com/feed/',
    source_type: 'rss',
    credibility_score: 0.90,
  },
  {
    name: 'The Gradient',
    url: 'https://thegradient.pub',
    feed_url: 'https://thegradient.pub/rss/',
    source_type: 'rss',
    credibility_score: 0.88,
  },
  {
    name: 'Import AI (Jack Clark)',
    url: 'https://importai.substack.com',
    feed_url: 'https://importai.substack.com/feed',
    source_type: 'rss',
    credibility_score: 0.90,
  },
  {
    name: 'VentureBeat AI',
    url: 'https://venturebeat.com/category/ai',
    feed_url: 'https://venturebeat.com/category/ai/feed/',
    source_type: 'rss',
    credibility_score: 0.78,
  },
  {
    name: 'Trail of Bits Blog',
    url: 'https://blog.trailofbits.com',
    feed_url: 'https://blog.trailofbits.com/feed/',
    source_type: 'rss',
    credibility_score: 0.93,
  },
  {
    name: 'WIRED – Security',
    url: 'https://www.wired.com/category/security',
    feed_url: 'https://www.wired.com/feed/category/security/latest/rss',
    source_type: 'rss',
    credibility_score: 0.83,
  },

  // App Security Learning
  {
    name: 'NCC Group Research',
    url: 'https://research.nccgroup.com',
    feed_url: 'https://research.nccgroup.com/feed/',
    source_type: 'rss',
    credibility_score: 0.92,
  },
  {
    name: 'HackerOne Hacker101',
    url: 'https://www.hackerone.com/blog',
    feed_url: 'https://www.hackerone.com/blog.rss',
    source_type: 'rss',
    credibility_score: 0.85,
  },
  {
    name: 'Checkmarx Blog',
    url: 'https://checkmarx.com/blog',
    feed_url: 'https://checkmarx.com/blog/feed/',
    source_type: 'rss',
    credibility_score: 0.82,
  },
  {
    name: 'F5 Labs',
    url: 'https://www.f5.com/labs',
    feed_url: 'https://www.f5.com/labs/rss/articles',
    source_type: 'rss',
    credibility_score: 0.86,
  },
  {
    name: 'Secureworks Blog',
    url: 'https://www.secureworks.com/blog',
    feed_url: 'https://www.secureworks.com/blog/feed',
    source_type: 'rss',
    credibility_score: 0.85,
  },

  // Industry News & Analyst
  {
    name: 'Gartner Security Blog',
    url: 'https://blogs.gartner.com/security',
    feed_url: 'https://blogs.gartner.com/security/feed/',
    source_type: 'rss',
    credibility_score: 0.88,
  },
  {
    name: 'SecurityWeek',
    url: 'https://www.securityweek.com',
    feed_url: 'https://www.securityweek.com/feed/',
    source_type: 'rss',
    credibility_score: 0.82,
  },
  {
    name: 'Infosecurity Magazine',
    url: 'https://www.infosecurity-magazine.com',
    feed_url: 'https://www.infosecurity-magazine.com/rss/news/',
    source_type: 'rss',
    credibility_score: 0.80,
  },
  {
    name: 'CSO Online',
    url: 'https://www.csoonline.com',
    feed_url: 'https://www.csoonline.com/feed/',
    source_type: 'rss',
    credibility_score: 0.80,
  },
  {
    name: 'BankInfoSecurity',
    url: 'https://www.bankinfosecurity.com',
    feed_url: 'https://www.bankinfosecurity.com/rss',
    source_type: 'rss',
    credibility_score: 0.82,
  },

  // IAM – more specialists & vendors
  {
    name: 'SailPoint Blog',
    url: 'https://www.sailpoint.com/blog',
    feed_url: 'https://www.sailpoint.com/blog/feed/',
    source_type: 'rss',
    credibility_score: 0.83,
  },
  {
    name: 'Saviynt Blog',
    url: 'https://saviynt.com/blog',
    feed_url: 'https://saviynt.com/blog/feed/',
    source_type: 'rss',
    credibility_score: 0.82,
  },
  {
    name: 'One Identity Blog',
    url: 'https://www.oneidentity.com/community/blogs',
    feed_url: 'https://www.oneidentity.com/community/blogs/rss',
    source_type: 'rss',
    credibility_score: 0.81,
  },
  {
    name: 'Stytch Blog (Passwordless / OIDC)',
    url: 'https://stytch.com/blog',
    feed_url: 'https://stytch.com/blog/feed/',
    source_type: 'rss',
    credibility_score: 0.80,
  },
  {
    name: 'Permit.io Blog (Authorization / ABAC / ReBAC)',
    url: 'https://www.permit.io/blog',
    feed_url: 'https://www.permit.io/blog/rss.xml',
    source_type: 'rss',
    credibility_score: 0.80,
  },
  {
    name: 'WSO2 Identity & Access Blog',
    url: 'https://wso2.com/blogs/thesource/identity-access-management',
    feed_url: 'https://wso2.com/blogs/thesource/feed/',
    source_type: 'rss',
    credibility_score: 0.82,
  },
  {
    name: 'Curity Blog (OAuth / OIDC)',
    url: 'https://curity.io/blog',
    feed_url: 'https://curity.io/blog/index.xml',
    source_type: 'rss',
    credibility_score: 0.87,
  },
  {
    name: 'Justin Richer (OAuth WG)',
    url: 'https://justin.richer.org/blog',
    feed_url: 'https://justin.richer.org/blog/feed/',
    source_type: 'rss',
    credibility_score: 0.91,
  },
  {
    name: 'Trusona Blog (Passwordless)',
    url: 'https://www.trusona.com/blog',
    feed_url: 'https://www.trusona.com/blog/feed/',
    source_type: 'rss',
    credibility_score: 0.78,
  },
  {
    name: 'FIDO Alliance News',
    url: 'https://fidoalliance.org/news',
    feed_url: 'https://fidoalliance.org/feed/',
    source_type: 'rss',
    credibility_score: 0.93,
  },

  // AI – research & safety
  {
    name: 'Anthropic Blog',
    url: 'https://www.anthropic.com/news',
    feed_url: 'https://www.anthropic.com/rss.xml',
    source_type: 'rss',
    credibility_score: 0.95,
  },
  {
    name: 'OpenAI Blog',
    url: 'https://openai.com/blog',
    feed_url: 'https://openai.com/blog/rss.xml',
    source_type: 'rss',
    credibility_score: 0.94,
  },
  {
    name: 'Hugging Face Blog',
    url: 'https://huggingface.co/blog',
    feed_url: 'https://huggingface.co/blog/feed.xml',
    source_type: 'atom',
    credibility_score: 0.88,
  },
  {
    name: 'The Allen Institute for AI Blog',
    url: 'https://allenai.org/blog',
    feed_url: 'https://allenai.org/blog/feed.xml',
    source_type: 'rss',
    credibility_score: 0.90,
  },
  {
    name: 'AI Snake Oil (Princeton)',
    url: 'https://aisnakeoil.substack.com',
    feed_url: 'https://aisnakeoil.substack.com/feed',
    source_type: 'rss',
    credibility_score: 0.88,
  },
  {
    name: 'Simon Willison Blog (LLMs / AI)',
    url: 'https://simonwillison.net',
    feed_url: 'https://simonwillison.net/atom/entries/',
    source_type: 'atom',
    credibility_score: 0.90,
  },
  {
    name: 'Last Week in AI',
    url: 'https://lastweekin.ai',
    feed_url: 'https://lastweekin.ai/feed',
    source_type: 'rss',
    credibility_score: 0.85,
  },
  {
    name: 'NIST AI Blog',
    url: 'https://www.nist.gov/artificial-intelligence',
    feed_url: 'https://www.nist.gov/blogs/cybersecurity-insights/rss.xml',
    source_type: 'rss',
    credibility_score: 0.92,
  },

  // App Security – more depth
  {
    name: 'Rapid7 Blog',
    url: 'https://www.rapid7.com/blog',
    feed_url: 'https://www.rapid7.com/blog/rss/',
    source_type: 'rss',
    credibility_score: 0.86,
  },
  {
    name: 'Tenable Blog',
    url: 'https://www.tenable.com/blog',
    feed_url: 'https://www.tenable.com/blog/feed',
    source_type: 'rss',
    credibility_score: 0.87,
  },
  {
    name: 'Veracode Blog',
    url: 'https://www.veracode.com/blog',
    feed_url: 'https://www.veracode.com/blog/feed',
    source_type: 'rss',
    credibility_score: 0.84,
  },
  {
    name: 'Bishop Fox Blog',
    url: 'https://bishopfox.com/blog',
    feed_url: 'https://bishopfox.com/blog/feed',
    source_type: 'rss',
    credibility_score: 0.88,
  },
  {
    name: 'Bugcrowd Blog',
    url: 'https://www.bugcrowd.com/blog',
    feed_url: 'https://www.bugcrowd.com/blog/feed/',
    source_type: 'rss',
    credibility_score: 0.83,
  },
  {
    name: 'Semgrep Blog (SAST / code security)',
    url: 'https://semgrep.dev/blog',
    feed_url: 'https://semgrep.dev/blog/feed.xml',
    source_type: 'rss',
    credibility_score: 0.87,
  },
  {
    name: 'Sonatype Blog (supply chain)',
    url: 'https://blog.sonatype.com',
    feed_url: 'https://blog.sonatype.com/rss.xml',
    source_type: 'rss',
    credibility_score: 0.85,
  },
  {
    name: 'Socket.dev Blog (supply chain)',
    url: 'https://socket.dev/blog',
    feed_url: 'https://socket.dev/blog/rss.xml',
    source_type: 'rss',
    credibility_score: 0.86,
  },

  // Industry & Analyst – more breadth
  {
    name: 'SC Magazine',
    url: 'https://www.scmagazine.com',
    feed_url: 'https://www.scmagazine.com/feed/',
    source_type: 'rss',
    credibility_score: 0.80,
  },
  {
    name: 'Help Net Security',
    url: 'https://www.helpnetsecurity.com',
    feed_url: 'https://www.helpnetsecurity.com/feed/',
    source_type: 'rss',
    credibility_score: 0.80,
  },
  {
    name: 'ZDNet Security',
    url: 'https://www.zdnet.com/topic/security',
    feed_url: 'https://www.zdnet.com/topic/security/rss.xml',
    source_type: 'rss',
    credibility_score: 0.80,
  },
  {
    name: 'Forrester Security Blog',
    url: 'https://www.forrester.com/blogs/category/security-risk',
    feed_url: 'https://www.forrester.com/blogs/category/security-risk/feed/',
    source_type: 'rss',
    credibility_score: 0.87,
  },
  {
    name: 'SANS Internet Storm Center',
    url: 'https://isc.sans.edu',
    feed_url: 'https://isc.sans.edu/rssfeed.xml',
    source_type: 'rss',
    credibility_score: 0.91,
  },
  {
    name: 'Recorded Future Blog',
    url: 'https://www.recordedfuture.com/blog',
    feed_url: 'https://www.recordedfuture.com/blog/feed',
    source_type: 'rss',
    credibility_score: 0.87,
  },
  {
    name: 'CrowdStrike Blog',
    url: 'https://www.crowdstrike.com/blog',
    feed_url: 'https://www.crowdstrike.com/blog/feed/',
    source_type: 'rss',
    credibility_score: 0.88,
  },
  {
    name: 'Mandiant Blog',
    url: 'https://www.mandiant.com/resources/blog',
    feed_url: 'https://www.mandiant.com/resources/blog/feed/',
    source_type: 'rss',
    credibility_score: 0.92,
  },
];
